<Project Sdk="Meziantou.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>deltabuild</ToolCommandName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Build" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" />
    <PackageReference Include="Microsoft.VisualStudio.SolutionPersistence" />
    <PackageReference Include="Meziantou.Framework.FullPath" />
    <PackageReference Include="Meziantou.Framework.Globbing" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
</Project>
