<Project Sdk="Meziantou.NET.Sdk.Test">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.InlineSnapshotTesting" />
    <PackageReference Include="Meziantou.Framework.TemporaryDirectory" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Meziantou.DeltaBuild\Meziantou.DeltaBuild.csproj" />
  </ItemGroup>
</Project>
